// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://howkwfepwuxezxhnxtfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhvd2t3ZmVwd3V4ZXp4aG54dGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjU5NzksImV4cCI6MjA3Mzk0MTk3OX0.prmaxB1nRdUD7X1TAHOvS59BAKTIwIGpkVZfGDlsmUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});